services:
    backend:
        image: 'job-seeker'
        container_name: 'job-seeker_back'
        depends_on:
            - postgresql
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/job-seeker
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=postgres
            - SPRING_JPA_HIBERNATE_DDL_AUTO=update
            - SPRING_JPA_SHOW_SQL=true
        ports:
            - 8080:8080
    postgresql:
        image: 'postgres'
        container_name: 'job-seeker_db'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=job-seeker
        ports:
            - 1234:5432

    redis:
        image: 'redis:latest'
        container_name: 'job-seeker_redis'
        environment:
            - REDIS_PASSWORD=redis
        ports:
            - 6379:6379

    minio:
        image: 'minio/minio'
        container_name: 'job-seeker_minio'
        environment:
            MINIO_ROOT_USER: minioadmin
            MINIO_ROOT_PASSWORD: minioadmin
        volumes:
            - minio_data1:/data
        ports:
            - 9000:9000
            - 9001:9001
        command: server /data --console-address ":9001"

volumes:
    minio_data1:
