spring:
    application:
        name: pet-project
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true


    datasource:
        url: ${DB_URL:jdbc:postgresql://localhost:1234/job-seeker}
        username: ${DB_USERNAME:postgres}
        password: ${DB_PASSWORD:postgres}
    flyway:
        url: ${DB_URL:jdbc:postgresql://localhost:1234/job-seeker}
        user: ${DB_USERNAME:postgres}
        password: ${DB_PASSWORD:postgres}
        locations: classpath:db/migration
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
    data:
        redis:
            host: localhost
            port: 6379
            password: redis
    cache:
        type: redis
        redis:
            time-to-live: 1200s
server:
    port: 8080

minio:
    url: ${MINIO_URL:http://localhost:9000}
    access-key: ${MINIO_ACCESS_KEY:CbHf6ebzFATccgVWwGXA}
    secret-key: ${MINIO_SECRET_KEY:FS8l763NEx8nappO0FcKC7rKhRBlyzVsfaUemVPx}
    bucket-name: ${MINIO_BUCKET_NAME:job-seeker}

#logging:
#    level:
#        root: INFO
#    pattern:
#        file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{35} - %msg%n"
#    file:
#        name: pet-project.log


