spring:
    application:
        name: pet-project
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
    datasource:
        username: ${DB_USERNAME}
        url: ${DB_URL}
        password: ${DB_PASSWORD}
    flyway:
        url: ${DB_URL}
        user: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        locations: classpath:db
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
server:
    port: 8080

#logging:
#    level:
#        root: INFO
#    pattern:
#        file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{35} - %msg%n"
#    file:
#        name: pet-project.log


