DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM ROLES WHERE NAME = 'ROLE_USER') THEN
        INSERT INTO ROLES (ID, NAME) VALUES (2, 'ROLE_USER');
END IF;

    IF NOT EXISTS (SELECT 1 FROM ROLES WHERE NAME = 'ROLE_ADMIN') THEN
        INSERT INTO ROLES (ID, NAME) VALUES (1, 'ROLE_ADMIN');
END IF;

    IF NOT EXISTS (SELECT 1 FROM ROLES WHERE NAME = 'ROLE_HR') THEN
        INSERT INTO ROLES (ID, NAME) VALUES (3, 'ROLE_HR');
END IF;
END $$;


DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM USERS WHERE EMAIL = 'admin@example.com') THEN
        INSERT INTO USERS (NAME, SURNAME, EMAIL, PASSWORD, DATE_OF_REGISTRATION)
        VALUES ('Admin', 'User', 'admin@example.com', '$2a$12$1Be/fD49QTH7tPaYMMIZrOerD6IBW7gnvAbDEnLEOrQkJljbWBjJq', CURRENT_TIMESTAMP);

INSERT INTO USERS_ROLES (USER_ID, ROLES_ID)
SELECT ID, (SELECT ID FROM ROLES WHERE NAME = 'ROLE_ADMIN') FROM USERS WHERE EMAIL = 'admin@example.com';
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM USERS WHERE EMAIL = 'user@example.com') THEN
        INSERT INTO USERS (NAME, SURNAME, EMAIL, PASSWORD, DATE_OF_REGISTRATION)
        VALUES ('User', 'Test', 'user@example.com', '$2a$12$8NrnnHUcKPjy9O6iYWffhuGsBFNImaQHCxAUcaz.iSPMZsUlRE2Mm', CURRENT_TIMESTAMP);
INSERT INTO USERS_ROLES (USER_ID, ROLES_ID)
SELECT ID, (SELECT ID FROM ROLES WHERE NAME = 'ROLE_USER') FROM USERS WHERE EMAIL = 'user@example.com';
END IF;
END $$;
